////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace HRDC
//{


//    public partial class Attendance
//    {

//        /// <summary>
//        /// form1 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

//        /// <summary>
//        /// lblSelect control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Label lblSelect;

//        /// <summary>
//        /// ddlTrainingSessions control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.DropDownList ddlTrainingSessions;

//        /// <summary>
//        /// btnLoad control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnLoad;

//        /// <summary>
//        /// gvAttendance control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.GridView gvAttendance;

//        /// <summary>
//        /// btnSubmit control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnSubmit;

//        /// <summary>
//        /// lblMessage control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Label lblMessage;
//    }
//}

using System;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Web.UI.WebControls;

namespace HRDC
{
    public partial class Attendance : System.Web.UI.Page
    {
        string connStr = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
                LoadTrainingSessions();
        }

        private void LoadTrainingSessions()
        {
            using (SqlConnection con = new SqlConnection(connStr))
            {
                SqlCommand cmd = new SqlCommand("SELECT TrainingID, Title FROM TrainingPrograms", con);
                con.Open();
                SqlDataReader reader = cmd.ExecuteReader();
                ddlTrainingSessions.DataSource = reader;
                ddlTrainingSessions.DataTextField = "Title";
                ddlTrainingSessions.DataValueField = "TrainingID";
                ddlTrainingSessions.DataBind();
            }
        }

        protected void btnLoad_Click(object sender, EventArgs e)
        {
            int trainingId = Convert.ToInt32(ddlTrainingSessions.SelectedValue);
            using (SqlConnection con = new SqlConnection(connStr))
            {
                SqlDataAdapter da = new SqlDataAdapter(
                    "SELECT e.EmployeeId, e.Name FROM Employees e " +
                    "JOIN Registrations r ON e.EmployeeId = r.EmployeeId " +
                    "WHERE r.TrainingId = @tid AND r.Status = 'Approved'", con);
                da.SelectCommand.Parameters.AddWithValue("@tid", trainingId);
                DataTable dt = new DataTable();
                da.Fill(dt);
                gvAttendance.DataSource = dt;
                gvAttendance.DataBind();
            }
        }

        protected void btnSubmit_Click(object sender, EventArgs e)
        {
            int trainingId = Convert.ToInt32(ddlTrainingSessions.SelectedValue);
            DateTime today = DateTime.Today;

            using (SqlConnection con = new SqlConnection(connStr))
            {
                con.Open();
                foreach (GridViewRow row in gvAttendance.Rows)
                {
                    string employeeId = row.Cells[0].Text;
                    CheckBox chk = (CheckBox)row.FindControl("chkPresent");
                    bool isPresent = chk.Checked;

                    SqlCommand cmd = new SqlCommand(
                        "INSERT INTO Attendance (EmployeeId, TrainingId, Date, IsPresent) " +
                        "VALUES (@eid, @tid, @date, @present)", con);
                    cmd.Parameters.AddWithValue("@eid", employeeId);
                    cmd.Parameters.AddWithValue("@tid", trainingId);
                    cmd.Parameters.AddWithValue("@date", today);
                    cmd.Parameters.AddWithValue("@present", isPresent);
                    cmd.ExecuteNonQuery();
                }
                lblMessage.Text = "Attendance saved successfully!";
            }
        }
    }
}
